on: [pull_request]

name: CI

jobs:
  check:
    name: Lint and Build Check
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up the Rust toolchain with nightly version
      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      # Step 3: Set up sccache to speed up subsequent builds
      - name: Set up sccache
        uses: mozilla-actions/sccache-action@v0.0.5

      # Step 4: Check code formatting with rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check

      # Step 5: Run Clippy for linting
      - name: Run Clippy
        run: cargo clippy --all-features --all-targets -- -D warnings  # Treat warnings as errors

      # Step 6: Run cargo check to ensure the code compiles
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
